env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
mongo_uri: "mongodb://localhost:27017/core"
database: "mongo"
autoria_key: fake-autoria-key
http_server:
  address: "localhost:8082"
  timeout: 4s
  iddle_timeout: 60s

